---
site_name: "LAB-21170: Hands-On Flow Designer Lab: APIs, AI Agents, and MCP in Action"
site_description: "LAB-21170: Hands-On Flow Designer Lab: APIs, AI Agents, and MCP in Action"
site_author: Adam Weeks and Arunabh Bhattacharjee
copyright: Copyright &copy; 2026 Cisco
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - navigation.footer
    - search.suggest
    - content.code.copy
    - toc.integrate
  custom_dir: docs/overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: template_assets/webexLogo91.png
  favicon: template_assets/webex75.png
extra:
  generator: false
  repo: "https://github.com/WebexCC-SA/LAB-21170.git"
  site_event: test
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - template_assets/js/newLoad.js
  - template_assets/js/setInfo.js
plugins:
  - search
  - macros
  # - with-pdf:
  #     cover_title: LABXXX-1234
  #     cover_subtitle: My famous WebexOne Lab
  #     cover_logo: template_assets/wx1Splash_new.gif
  - glightbox:
      touchNavigation: true
      loop: false
      effect: fade
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: false
      skip_classes:
      - custom-skip-class-name
      auto_caption: true
      caption_position: top
markdown_extensions:
  - md_in_html
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - tables
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true
      
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - Home: index.md
  - Welcome: welcome.md
  - Lab:
      - Overview: overview.md
      - Checkpoint 1 - Lab access: lab1_getting_started.md
      - Checkpoints 2-3 - Flow Designer: lab2_flow_designer.md
      - Checkpoints 4-5 - Connect and test MCP: lab3_agent_registration.md
      - Checkpoints 6-8 - Register MCP and build agent: lab4_mcp_agent_studio.md
      - Checkpoint 9 - End-to-end test: lab5_end_to_end.md
      - Troubleshooting and completion: troubleshooting.md
      - Official references: references.md
      - Conclusion: conclusion.md
